AWSTemplateFormatVersion: 2010-09-09
Description: |
 Create Kittens website 

#Parameters:
  
Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH and HTTPS" 
      GroupName: "Web-Security-Group"
      SecurityGroupIngress: 
        - CidrIp: "0.0.0.0/0"
          FromPort: 80
          IpProtocol: "tcp"
          ToPort: 80
        - CidrIp: "0.0.0.0/0"
          FromPort: 22
          IpProtocol: "tcp"
          ToPort: 22
  WebServer:
    Type: AWS::EC2::Instance
    Properties:

      Tags: 
        - Key: "Name"
          Value: "Steve-server"
      ImageId: "ami-085ad6ae776d8f09c"
      KeyName: "My 1st keypair"
      InstanceType: "t2.micro"
      SecurityGroupIds: 
        - Fn::GetAtt: WebSecurityGroup.GroupId
      UserData: 
        Fn::Base64:
          |
            #!/bin/bash -x
            yum update -y
            yum install httpd -y
            cd /var/www/html

            FOLDER="https://raw.githubusercontent.com/steveriviere/my-repository/refs/heads/main/101-kittens-carousel-static-website-ec2/static-web"


            wget ${FOLDER}/index.html
            wget ${FOLDER}/cat0.jpg
            wget ${FOLDER}/cat1.jpg
            wget ${FOLDER}/cat2.jpg


            systemctl start httpd
            systemctl enable httpd

Outputs:

  WebSiteUrl:
    Description: Kitten Carroussel 
    Value:  !Join ["", ["http://", Fn::GetAtt WebServer.PublicDnsName]]


